MODEL: 
  NAME: 'clipfsar'
  BACKBONE: 'RN50'          # ["RN50", "ViT-B/16"]
  SEED: 18
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 1.5

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 4
  TASKS_PER_BATCH: 4

  TRAIN_EPISODES: 3010
  VAL_FREQ: 100
  CLASS_NAME: ['brush hair', 'catch', 'chew', 'clap', 'climb', 'climb stairs', 'dive', 'draw_sword', 'dribble', 'drink', 'fall floor', 'flic flac', 'handstand', 'hug', 'jump', 'kiss', 'pullup', 'punch', 'push', 'ride_bike', 'ride horse', 'shake_hands', 'shoot_bow', 'situp', 'stand', 'sword', 'sword exercise', 'throw', 'turn', 'walk', 'wave']
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: 'checkpoint/hmdb/1shot/clipmei/checkpoint_best.pt'
  CLASS_NAME: ['fencing', 'kick', 'kick ball', 'pick', 'pour', 'pushup', 'run', 'sit', 'smoke', 'talk']
  
DATA:
  DATASET: 'hmdb'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/mnt/home/lxy/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/hmdb/1shot/clipfsar'
  SAVE_FREQ: 20000

SOLVER:
  LR: 0.000002
  WEIGHT_DECAY: 5e-5
  OPTIM_METHOD: 'adam'   # ["adam", "sgd"]
