INFO: ''
DEBUG: false
# USE_AMP: true
MODEL: 
  NAME: 'clipspm'
  BACKBONE: 'RN50'          # ["RN50", "ViT-B/16"]
  SEED: 6

TRAIN:
  WAY: 5
  SHOT: 5
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 20010
  VAL_FREQ: 1000
  CLASS_NAME: ['water skiing', 'catching or throwing baseball', 'washing hands', 'opening bottle', 'doing nails', 'somersaulting', 'cooking chicken', 'riding unicycle', 'washing dishes', 'drop kicking', 'contact juggling', 'hopscotch', 'playing keyboard', 'weaving basket', 'pushing cart', 'giving or receiving award', 'bungee jumping', 'blowing out candles', 'making snowman', 'feeding birds', 'playing ukulele', 'driving tractor', 'dying hair', 'snowboarding', 'beatboxing', 'blowing glass', 'trapezing', 'shot put', 'shuffling cards', 'laughing', 'curling hair', 'bowling', 'country line dancing', 'eating burger', 'squat', 'playing didgeridoo', 'playing accordion', 'breakdancing', 'cleaning floor', 'playing ice hockey', 'playing xylophone', 'presenting weather forecast', 'sled dog racing', 'massaging back', 'jumping into pool', 'punching bag', 'reading book', 'shaving head', 'shaking head', 'using computer', 'jetskiing', 'playing badminton', 'biking through snow', 'sharpening pencil', 'waxing legs', 'slacklining', 'air drumming', 'arm wrestling', 'cheerleading', 'playing basketball', 'deadlifting', 'dribbling basketball', 'mowing lawn', 'surfing crowd']

TEST:
  ONLY_TEST: true
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: 'checkpoints_retain/kinetics/5shot/RN50/clipspm/checkpoint_best.pt'
  CLASS_NAME: ['stretching arm', 'hula hooping', 'playing drums', 'folding paper', 'ice skating', 'hurling (sport)', 'playing monopoly', 'tap dancing', 'unboxing', 'shearing sheep', 'dancing ballet', 'filling eyebrows', 'playing trumpet', 'diving cliff', 'riding elephant', 'dancing macarena', 'blasting sand', 'busking', 'pushing car', 'paragliding', 'side kick', 'dancing charleston', 'cutting watermelon', 'throwing axe']

DATA:
  DATASET: 'kinetics'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/mnt/home/lxy/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoints/kinetics/5shot/RN50/clipspm'
  SAVE_FREQ: 500

SOLVER:
  LR: 0.00001
  WEIGHT_DECAY: 5e-5
  OPTIM_METHOD: 'adam'   # ["adam", "sgd"]
